<table border="0" style="background:#eee; color:#333; border:solid 1px #000000;">
    <tr>
        <td colspan="2"><strong>Start now letter</strong></td>
    </tr>
    <tr>
        <td>%%name.title%%</td>
        <td>%%name.value%%</td>
    </tr>
    <tr>
        <td>%%email.title%%</td>
        <td>%%email.value%%</td>
    </tr>
    <tr>
        <td>%%short_resume.title%%</td>
        <td>%%short_resume.value%%</td>
    </tr>
    <tr>
        <td>%%cover_letter.title%%</td>
        <td>%%cover_letter.value%%</td>
    </tr>
    <tr>
        <td>%%phone.title%%</td>
        <td>%%phone.value%%</td>
    </tr>
    <tr>
        <td>%%soc_profile.title%%</td>
        <td>%%soc_profile.value%%</td>
    </tr>
    <tr>
        <td>%%website.title%%</td>
        <td>%%website.value%%</td>
    </tr>
</table>